### ISSUE TITLE
Missing error page

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio-docs#18]
When GBS crashes, there's a button that says "What can I do?" which links them to this page: [https://www.gbstudio.dev/docs/error/](https://www.gbstudio.dev/docs/error/)

Did this page ever exist? If not, what kind of actions should be available to users after their project has an error? Would love some suggestions.

**Comment by chrismaltby** [comment]
Only just seen this @DeerTears, did have the page on the old site but it got lost while migrating, I've moved it over now in #23  so that link works as expected now
