### ISSUE TITLE
Bring back the printable docs

### ISSUE THREAD

**Issue by jessemillar** [chrismaltby/gb-studio-docs#8]
The printable docs available in previous versions were great for printing but also were slightly easier to skim/search using Ctrl + F. Unfortunately, the search bar built in to the current documentation often doesn't take me to the content I need and if I had access to printable docs I could quickly skim all of them to find the section/phrase I need.

**Comment by proximitysound** [comment]
It looks like the tool used to create the docs (docusauras) has two pdf creation plugins available. I'll try to take a look at it if Chris or others aren't able to.

https://github.com/kohheepeace/mr-pdf

https://github.com/signcl/docusaurus-prince-pdf

**Comment by chrismaltby** [comment]
Thanks for the suggestions @proximitysound I've used [docusaurus-prince-pdf](https://github.com/signcl/docusaurus-prince-pdf) to generate a PDF version of the site and added a link to it at the bottom of https://www.gbstudio.dev/docs/

https://www.gbstudio.dev/assets/files/www.gbstudio.dev-docs-7d68477643c902b73121a87f0963cbc0.pdf
